from .login_view import *;
from .add_employee import *;
from .home import *;
from .add_permission import *;
from .ChangePassword import *;
from .AdmissonchargesMaster import *;
from .DepartmentMaster import *;
from .MainFloorMaster import *;
from .RoomTypeMasterView import *;
from .RoomMasterView import *;  
from .BedsMasterView import *;
from .StateMasterView import *;
from .DistrictMasterView import *;  
from .ServiceMasterView import *;
from .ProMasterView import *;
from .SpecialityMasterView import *;    
from .DoctorMasterView import *;   
from .RefDoctorMasterView import *; 
from .ServiceTypeMasterView import *
from .CaseTypeMasterView import *;
from .OpPatientRegistrationView import *    

from .DoctorConsultationView import *;
from .SearchUHIDView import *
from .PayeeMasterView import *  
from .IpRegistrationView import *   
from .BankMasterView import *   
from .create_prescription import *  
from .Prescription1 import *
from .check_gpt_version import *       
from .Prescription3 import *   
from .Prescription4 import *  
from .OPProcedureView import *  
from .OpInvestigationView import *  
from .InvestigationMasterView import *  
from .InvDepartmentMasterView import *;
from .InvGroupMasterView import *;
from .SelectingPatient import *;
from .check_basic import *  
from .OpPayment import *    
from .PrintPages import * 
from .CancellationView import *   
from .UserwiseCollection import *   
from .RefundView import *    
from .RolesPage import *    
from .InvestdetailsView import *    
from .InvestigationDetailsMaster import *   
from .LabEntry import * 
from .Modifylab import *    
from .ConcessionReport import *
from .OpModify import * 
from .RegistrationUhidFinder import *   
from .ExpenditureMaster import *        
from .InvestigationReportView import *  
from .patinfo import *  
from .ProReport import *    
from .CancellationReport import *   
from .DueReports import *
from .daycollection import *
from .Refdoctorreport import *
from .DayWiseDocReportView import *
from .CaseWiseReportView import *    
from .ServiceReportView import *    
from .InvCal import *   
from .InvestDeptWiseReport import * 
from .DailyInvestigations import *  
from .DailyProcedures import *  
from .paymentmodeupdate import *  

from .SittingsPageView import *     