# Generated by Django 5.2.7 on 2025-11-24 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorconsultation',
            name='pro',
        ),
        migrations.RemoveField(
            model_name='doctorconsultation',
            name='refdoc',
        ),
        migrations.AlterField(
            model_name='doctorconsultation',
            name='agetype',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='doctorconsultation',
            name='concreason',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='doctorconsultation',
            name='consulttype',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='doctorconsultation',
            name='paymode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='doctorconsultation',
            name='visittype',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
