# Generated by Django 5.2.7 on 2025-11-25 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospApp', '0002_remove_doctorconsultation_pro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctormaster',
            name='phoneno',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterModelTable(
            name='specialitymaster',
            table='speciality_master',
        ),
    ]
