# Generated by Django 5.2.7 on 2025-11-27 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospApp', '0003_alter_doctormaster_phoneno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorconsultation',
            name='opno',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
