# Generated by Django 5.2.7 on 2025-11-28 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospApp', '0004_doctorconsultation_opno'),
    ]

    operations = [
        migrations.AddField(
            model_name='oppatientregistration',
            name='alternatephone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
