# Generated by Django 5.2.7 on 2025-11-28 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospApp', '0005_oppatientregistration_alternatephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctormaster',
            name='revisittime',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
