# Generated by Django 5.2.7 on 2025-12-01 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospApp', '0006_doctormaster_revisittime'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctormaster',
            name='qualification',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='doctormaster',
            name='regno',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
