# Generated by Django 5.2.7 on 2025-12-02 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospApp', '0007_doctormaster_qualification_doctormaster_regno'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblInvestigationDetails',
            fields=[
                ('uhid', models.CharField(max_length=50)),
                ('invname', models.CharField(blank=True, max_length=150, null=True)),
                ('cost', models.IntegerField(blank=True, null=True)),
                ('generateddate', models.DateTimeField(blank=True, null=True)),
                ('createdby', models.CharField(blank=True, max_length=50, null=True)),
                ('updatedby', models.CharField(blank=True, max_length=50, null=True)),
                ('updatedtime', models.DateTimeField(blank=True, null=True)),
                ('billno', models.IntegerField(blank=True, null=True)),
                ('ipno', models.CharField(blank=True, max_length=20, null=True)),
                ('patname', models.CharField(blank=True, max_length=150, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('agetype', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('doc', models.CharField(blank=True, max_length=100, null=True)),
                ('refdoc', models.CharField(blank=True, max_length=100, null=True)),
                ('ID_PK', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=30, null=True)),
                ('concessionamt', models.IntegerField(blank=True, null=True)),
                ('concreason', models.CharField(blank=True, max_length=150, null=True)),
                ('paidamt', models.IntegerField(blank=True, null=True)),
                ('due', models.IntegerField(blank=True, null=True)),
                ('refundate', models.DateTimeField(blank=True, null=True)),
                ('refund', models.CharField(blank=True, max_length=2, null=True)),
                ('paymentmode', models.CharField(blank=True, max_length=20, null=True)),
                ('cardname', models.CharField(blank=True, max_length=100, null=True)),
                ('active', models.CharField(blank=True, max_length=1, null=True)),
                ('cancelreson', models.CharField(blank=True, max_length=30, null=True)),
                ('dept', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'tblInvestigationDetails',
            },
        ),
    ]
