# Generated by Django 5.2.7 on 2025-12-03 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospApp', '0008_tblinvestigationdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='patid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='uhid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
