# Generated by Django 5.2.7 on 2025-12-04 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospApp', '0009_prescription_patid_prescription_uhid'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='consult',
            field=models.ForeignKey(blank=True, help_text='The consultation this prescription belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='hospApp.doctorconsultation'),
        ),
    ]
