# Generated by Django 5.2.7 on 2025-12-04 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospApp', '0010_prescription_consult'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='stroke_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
