# Generated by Django 5.2.7 on 2025-12-05 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospApp', '0011_prescription_stroke_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription3',
            name='consult',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audio_prescriptions', to='hospApp.doctorconsultation'),
        ),
    ]
