# Generated by Django 5.2.7 on 2025-12-05 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospApp', '0012_prescription3_consult'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription3',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
