# Generated by Django 5.2.7 on 2025-12-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospApp', '0013_prescription3_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='bp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='pr',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='spo2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='temp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='weight',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
