# Generated by Django 5.2.7 on 2025-12-08 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospApp', '0014_prescription_bp_prescription_pr_prescription_spo2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription3',
            name='bp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='prescription3',
            name='pr',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='prescription3',
            name='spo2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='prescription3',
            name='temp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='prescription3',
            name='weight',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
