# Generated by Django 5.2.7 on 2025-12-08 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospApp', '0015_prescription3_bp_prescription3_pr_prescription3_spo2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorconsultation',
            name='is_prescription_done',
            field=models.BooleanField(default=False),
        ),
    ]
