# Generated by Django 5.2.7 on 2025-12-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospApp', '0016_doctorconsultation_is_prescription_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorconsultation',
            name='is_revisit',
            field=models.BooleanField(default=False),
        ),
    ]
