# Generated by Django 5.2.7 on 2025-12-10 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospApp', '0017_doctorconsultation_is_revisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorconsultation',
            name='previous_consult',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisit_records', to='hospApp.doctorconsultation'),
        ),
    ]
