# Generated by Django 5.2.7 on 2025-12-12 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospApp', '0018_doctorconsultation_previous_consult'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='oppatientregistration',
            table='oppatient_registration',
        ),
    ]
