# Generated by Django 5.2.7 on 2025-12-12 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospApp', '0019_alter_oppatientregistration_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblinvestigationdetails',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
