# Generated by Django 5.2.7 on 2025-12-13 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospApp', '0020_tblinvestigationdetails_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblinvestigationdetails',
            name='doctor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
