# Generated by Django 5.2.7 on 2025-12-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospApp', '0021_tblinvestigationdetails_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillMaster',
            fields=[
                ('billno', models.BigAutoField(primary_key=True, serialize=False)),
                ('bill_date', models.DateField(auto_now_add=True)),
                ('bill_type', models.CharField(choices=[('CONSULTATION', 'Consultation'), ('INVESTIGATION', 'Investigation'), ('PHARMACY', 'Pharmacy')], max_length=20)),
                ('uhid', models.CharField(max_length=50)),
                ('created_by', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'bill_master',
            },
        ),
    ]
