# Generated by Django 5.2.7 on 2025-12-18 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospApp', '0022_billmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblServices',
            fields=[
                ('id', models.AutoField(db_column='ID_PK', primary_key=True, serialize=False)),
                ('uhid', models.CharField(max_length=20)),
                ('services', models.CharField(max_length=100)),
                ('services_typename', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('generateddate', models.DateTimeField(blank=True, null=True)),
                ('generatedtime', models.DateTimeField(blank=True, null=True)),
                ('createdby', models.CharField(blank=True, max_length=50, null=True)),
                ('createddate', models.DateTimeField(blank=True, null=True)),
                ('updatedby', models.CharField(blank=True, max_length=100, null=True)),
                ('updateddate', models.DateTimeField(blank=True, null=True)),
                ('billno', models.IntegerField(blank=True, null=True)),
                ('pattype', models.CharField(blank=True, max_length=15, null=True)),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('concessionamt', models.IntegerField(blank=True, null=True)),
                ('concreason', models.CharField(blank=True, max_length=150, null=True)),
                ('paidamt', models.IntegerField(blank=True, null=True)),
                ('due', models.IntegerField(blank=True, null=True)),
                ('qty', models.IntegerField(blank=True, null=True)),
                ('ipno', models.CharField(blank=True, max_length=20, null=True)),
                ('isactive', models.CharField(blank=True, max_length=1, null=True)),
                ('cardname', models.CharField(blank=True, max_length=100, null=True)),
                ('paymentmode', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'tblservices',
            },
        ),
    ]
