# Generated by Django 5.2.7 on 2025-12-18 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospApp', '0023_tblservices'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblservices',
            name='doctor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
