# Generated by Django 5.2.7 on 2025-12-19 09:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospApp', '0024_tblservices_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
