# Generated by Django 5.2.7 on 2025-12-20 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospApp', '0025_alter_prescription_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientVitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('bp', models.CharField(blank=True, max_length=10, null=True)),
                ('pulse', models.IntegerField(blank=True, null=True)),
                ('spo2', models.IntegerField(blank=True, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='hospApp.doctorconsultation')),
            ],
        ),
    ]
