# Generated by Django 5.2.7 on 2025-12-22 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospApp', '0027_prescription_updated_at_alter_prescription_consult_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription3',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='prescription3',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]