# Generated by Django 5.2.7 on 2025-12-22 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospApp', '0028_prescription3_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription3',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
