# Generated by Django 5.2.7 on 2025-12-26 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospApp', '0029_alter_prescription3_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uhid', models.CharField(max_length=50)),
                ('num', models.CharField(blank=True, max_length=50, null=True)),
                ('patname', models.CharField(blank=True, max_length=150, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('agetype', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('billdate', models.DateTimeField(blank=True, null=True)),
                ('totalamt', models.IntegerField(blank=True, null=True)),
                ('paidamt', models.IntegerField(blank=True, null=True)),
                ('balance', models.IntegerField(blank=True, null=True)),
                ('patamt', models.IntegerField(blank=True, null=True)),
                ('userid', models.CharField(blank=True, max_length=50, null=True)),
                ('updatedby', models.CharField(blank=True, max_length=50, null=True)),
                ('updateddate', models.DateTimeField(blank=True, null=True)),
                ('billno', models.IntegerField(blank=True, null=True)),
                ('due', models.IntegerField(blank=True, null=True)),
                ('invbillno', models.IntegerField(blank=True, null=True)),
                ('cardname', models.CharField(blank=True, max_length=100, null=True)),
                ('paymentmode', models.CharField(blank=True, max_length=20, null=True)),
                ('concreason', models.CharField(blank=True, max_length=50, null=True)),
                ('concession', models.IntegerField(blank=True, null=True)),
                ('preconcession', models.IntegerField(blank=True, null=True)),
                ('towords', models.CharField(blank=True, max_length=30, null=True)),
                ('recordno', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'opPayments',
            },
        ),
    ]
