# Generated by Django 5.2.7 on 2026-01-03 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospApp', '0030_oppayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblOpCancellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uhid', models.CharField(max_length=50)),
                ('billno', models.IntegerField()),
                ('billdate', models.DateTimeField(blank=True, null=True)),
                ('patname', models.CharField(blank=True, max_length=150, null=True)),
                ('opno', models.CharField(blank=True, max_length=1, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
                ('phoneno', models.CharField(blank=True, max_length=20, null=True)),
                ('floorid', models.CharField(blank=True, max_length=20, null=True)),
                ('roomid', models.CharField(blank=True, max_length=20, null=True)),
                ('bedid', models.CharField(blank=True, max_length=20, null=True)),
                ('totalamt', models.IntegerField()),
                ('Reason', models.CharField(blank=True, max_length=150, null=True)),
                ('userid', models.CharField(max_length=50)),
                ('createddate', models.DateTimeField(blank=True, null=True)),
                ('regdate', models.CharField(blank=True, max_length=30, null=True)),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('concessionamt', models.IntegerField(blank=True, null=True)),
                ('amtpaid', models.IntegerField(blank=True, null=True)),
                ('refundamt', models.IntegerField(blank=True, null=True)),
                ('bal', models.IntegerField(blank=True, null=True)),
                ('createdby', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'tblOpCancellation',
            },
        ),
    ]
