# Generated by Django 5.2.7 on 2026-01-05 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospApp', '0031_tblopcancellation'),
    ]

    operations = [
        migrations.AddField(
            model_name='oppayment',
            name='active',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
