# Generated by Django 5.2.7 on 2026-01-05 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospApp', '0032_oppayment_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='billmaster',
            name='active',
            field=models.CharField(blank=True, default='Y', max_length=1),
        ),
    ]
