# Generated by Django 5.2.7 on 2026-01-08 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospApp', '0033_billmaster_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblRefund',
            fields=[
                ('uhid', models.CharField(db_column='uhid', max_length=20)),
                ('patno', models.CharField(blank=True, db_column='patno', max_length=10, null=True)),
                ('patname', models.CharField(blank=True, db_column='patname', max_length=50, null=True)),
                ('billno', models.IntegerField(blank=True, db_column='billno', null=True)),
                ('billtime', models.DateTimeField(blank=True, db_column='billtime', null=True)),
                ('totalamt', models.IntegerField(blank=True, db_column='totalamt', null=True)),
                ('refund', models.IntegerField(blank=True, db_column='refund', null=True)),
                ('amtpaid', models.IntegerField(blank=True, db_column='amtpaid', null=True)),
                ('balance', models.IntegerField(blank=True, db_column='balance', null=True)),
                ('reason', models.CharField(blank=True, db_column='reason', max_length=150, null=True)),
                ('usercode', models.CharField(db_column='usercode', max_length=50)),
                ('createdtime', models.DateTimeField(blank=True, db_column='createdtime', null=True)),
                ('updatedby', models.CharField(blank=True, db_column='updatedby', max_length=50, null=True)),
                ('updatedtime', models.DateTimeField(blank=True, db_column='updatedtime', null=True)),
                ('type', models.CharField(blank=True, db_column='type', max_length=20, null=True)),
                ('towords', models.CharField(blank=True, db_column='towords', max_length=15, null=True)),
                ('createdby', models.CharField(blank=True, db_column='createdby', max_length=30, null=True)),
                ('id_pk', models.IntegerField(db_column='id_pk', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tblRefund',
            },
        ),
    ]
