# Generated by Django 5.2.7 on 2026-01-08 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ('hospApp', '0034_tblrefund'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainmenu',
            options={'ordering': ['display_order']},
        ),
        migrations.AlterModelOptions(
            name='submenu',
            options={'ordering': ['display_order']},
        ),
        migrations.AddField(
            model_name='tblroles',
            name='pages',
            field=models.ManyToManyField(blank=True, related_name='roles', to='hospApp.submenu'),
        ),
        migrations.AlterField(
            model_name='mainmenu',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='url',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterModelTable(
            name='mainmenu',
            table='hospapp_mainmenu',
        ),
        migrations.AlterModelTable(
            name='submenu',
            table='hospapp_submenu',
        ),
    ]
