# Generated by Django 5.2.7 on 2026-01-10 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospApp', '0036_alter_mainmenu_options_alter_submenu_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainmenu',
            options={},
        ),
        migrations.AlterModelOptions(
            name='submenu',
            options={},
        ),
        migrations.AlterField(
            model_name='mainmenu',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='url',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterModelTable(
            name='mainmenu',
            table=None,
        ),
        migrations.AlterModelTable(
            name='submenu',
            table=None,
        ),
    ]
