# Generated by Django 5.2.7 on 2026-01-10 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospApp', '0037_alter_mainmenu_options_alter_submenu_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submenu',
            name='is_header',
            field=models.BooleanField(default=False),
        ),
    ]
