# Generated by Django 5.2.7 on 2026-01-20 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospApp', '0038_submenu_is_header'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewInvMaster',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('invname', models.IntegerField()),
                ('test', models.CharField(blank=True, max_length=50, null=True)),
                ('units', models.CharField(blank=True, max_length=20, null=True)),
                ('normal', models.TextField(blank=True, null=True)),
                ('method', models.CharField(blank=True, max_length=200, null=True)),
                ('header', models.CharField(blank=True, max_length=50, null=True)),
                ('impression', models.TextField(blank=True, null=True)),
                ('defaults', models.TextField(blank=True, null=True)),
                ('submethod', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'newinvmaster',
            },
        ),
    ]
