# Generated by Django 5.2.7 on 2026-01-26 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospApp', '0039_newinvmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestigationReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('billno', models.CharField(max_length=20)),
                ('uhid', models.CharField(max_length=20)),
                ('patname', models.CharField(max_length=100)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('agetype', models.CharField(blank=True, max_length=10, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('doc', models.CharField(blank=True, max_length=100, null=True)),
                ('inv_id', models.IntegerField()),
                ('test', models.CharField(max_length=100)),
                ('result', models.CharField(blank=True, max_length=50, null=True)),
                ('units', models.CharField(blank=True, max_length=20, null=True)),
                ('normal', models.TextField(blank=True, null=True)),
                ('userid', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'investigation_report',
            },
        ),
        migrations.AlterModelOptions(
            name='newinvmaster',
            options={'managed': False},
        ),
    ]
