# Generated by Django 5.2.7 on 2026-01-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospApp', '0041_investigationreport_alter_newinvmaster_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigationreport',
            name='defaults',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investigationreport',
            name='header',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='investigationreport',
            name='impression',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investigationreport',
            name='method',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='investigationreport',
            name='submethod',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
