# Generated by Django 5.2.7 on 2026-01-28 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospApp', '0042_investigationreport_defaults_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigationreport',
            name='generateddate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
