# Generated by Django 5.2.7 on 2026-01-28 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospApp', '0043_investigationreport_generateddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblinvestigationdetails',
            name='generateddate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
