# Generated by Django 5.2.11 on 2026-03-17 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospApp', '0044_alter_tblinvestigationdetails_generateddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigationmaster',
            name='department_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investigations', to='hospApp.departmentphotomaster'),
        ),
    ]
