# Generated by Django 5.2.11 on 2026-03-17 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospApp', '0045_investigationmaster_department_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investigationmaster',
            name='department_fk',
        ),
        migrations.AlterField(
            model_name='investigationmaster',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospApp.departmentphotomaster'),
        ),
    ]
