# Generated by Django 5.2.11 on 2026-03-18 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospApp', '0046_remove_investigationmaster_department_fk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigationreport',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
