# Generated by Django 5.2.11 on 2026-04-01 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospApp', '0047_investigationreport_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigationreport',
            name='test',
            field=models.TextField(),
        ),
    ]
