# Generated by Django 5.2.11 on 2026-04-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospApp', '0049_alter_investigationreport_result_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('expenditure_name', models.CharField(max_length=100)),
            ],
        ),
    ]
