# Generated by Django 5.2.11 on 2026-04-06 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospApp', '0050_expenditure'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenditure',
            name='active',
            field=models.CharField(blank=True, default='Y', max_length=5, null=True),
        ),
    ]
