# Generated by Django 5.2.11 on 2026-04-07 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospApp', '0051_expenditure_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenditure',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expenditure',
            name='billno',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='expenditure',
            name='towards',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
