# Generated by Django 5.2.11 on 2026-04-07 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospApp', '0052_expenditure_amount_expenditure_billno_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenditure',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='expenditure',
            name='billno',
        ),
        migrations.RemoveField(
            model_name='expenditure',
            name='towards',
        ),
    ]
