# Generated by Django 5.2.11 on 2026-04-07 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospApp', '0053_remove_expenditure_amount_remove_expenditure_billno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenditureEntry',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('bill_no', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('towards', models.CharField(max_length=255)),
                ('expenditure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospApp.expenditure')),
            ],
        ),
    ]
