# Generated by Django 5.2.11 on 2026-04-07 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospApp', '0054_expenditureentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenditureentry',
            name='bill_no',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
