# Generated by Django 5.2.11 on 2026-04-07 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospApp', '0055_alter_expenditureentry_bill_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenditureentry',
            name='bill_no',
            field=models.IntegerField(unique=True),
        ),
    ]
