# Generated by Django 5.2.11 on 2026-04-07 07:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospApp', '0056_alter_expenditureentry_bill_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenditureentry',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
