# Generated by Django 5.2.11 on 2026-04-07 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospApp', '0057_expenditureentry_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenditureentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
