# Generated by Django 5.2.11 on 2026-04-07 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospApp', '0058_alter_expenditureentry_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenditureentry',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
