# Generated by Django 5.2.11 on 2026-04-14 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospApp', '0059_expenditureentry_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='submenu',
            name='is_menu',
            field=models.BooleanField(default=True),
        ),
    ]
