# Generated by Django 5.2.11 on 2026-04-23 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospApp', '0060_submenu_is_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblservices',
            name='doc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospApp.doctormaster'),
        ),
    ]
