# Generated by Django 5.2.11 on 2026-05-04 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospApp', '0061_tblservices_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenditureentry',
            name='active',
            field=models.CharField(blank=True, default='Y', max_length=1),
        ),
    ]
