# Generated by Django 5.2.11 on 2026-05-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospApp', '0062_expenditureentry_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenditureentry',
            name='reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='expenditureentry',
            name='user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
