# Generated by Django 5.2.11 on 2026-05-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospApp', '0063_expenditureentry_reason_expenditureentry_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenditureentry',
            name='selecteduser',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
