# Generated by Django 5.2.11 on 2026-05-18 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospApp', '0064_expenditureentry_selecteduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigationreport',
            name='is_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='oppatientregistration',
            name='title',
            field=models.CharField(choices=[('Mr', 'Mr.'), ('Mrs', 'Mrs.'), ('Ms', 'Ms.'), ('Miss', 'Miss.'), ('Baby', 'Baby')], default='Mr', max_length=10),
        ),
    ]
