# Generated by Django 5.2.11 on 2026-06-03 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospApp', '0065_investigationreport_is_check_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submenu',
            name='is_menu',
        ),
        migrations.AddField(
            model_name='departmentphotomaster',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        # mssql-django cannot alter IntegerField → AutoField directly.
        # If id_pk is already an IDENTITY column in SQL Server, this is safe to skip.
        migrations.RunSQL(
            sql="SELECT 1;",
            reverse_sql=migrations.RunSQL.noop,
        ),

    ]