# Generated by Django 5.2.11 on 2026-06-03 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospApp', '0066_remove_submenu_is_menu_departmentphotomaster_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentphotomaster',
            name='regno',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        # mssql-django cannot alter IntegerField → AutoField; column is already IDENTITY in DB
        migrations.RunSQL(
            sql="SELECT 1;",
            reverse_sql=migrations.RunSQL.noop,
        ),

    ]