# Generated by Django 5.2.11 on 2026-06-03 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospApp', '0067_departmentphotomaster_regno_alter_tblrefund_id_pk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmentphotomaster',
            name='photo',
        ),
        migrations.AddField(
            model_name='departmentphotomaster',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='department_signatures/'),
        ),
    ]
