# Generated by Django 5.2.11 on 2026-06-11 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospApp', '0068_remove_departmentphotomaster_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='test',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
