# Generated by Django 5.2.11 on 2026-06-11 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospApp', '0069_state_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='test',
        ),
    ]
