# Generated by Django 5.2.11 on 2026-06-12 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospApp', '0072_tblinvestigationdetails_cash_amt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblservices',
            name='cash_amt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tblservices',
            name='online_amt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tblservices',
            name='online_details',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tblservices',
            name='online_mode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
