# Generated by Django 5.2.11 on 2026-06-13 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospApp', '0074_oppayment_cash_amt_oppayment_online_amt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentModeUpdateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uhid', models.CharField(max_length=50)),
                ('patient_name', models.CharField(max_length=150)),
                ('bill_no', models.CharField(max_length=50)),
                ('bill_type', models.CharField(max_length=50)),
                ('old_online_mode', models.CharField(blank=True, max_length=100, null=True)),
                ('new_online_mode', models.CharField(blank=True, max_length=100, null=True)),
                ('old_reference', models.CharField(blank=True, max_length=200, null=True)),
                ('new_reference', models.CharField(blank=True, max_length=200, null=True)),
                ('updated_by', models.CharField(max_length=50)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
