# Generated by Django 5.2.11 on 2026-07-09 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospApp', '0076_alter_employee_address_alter_employee_emp_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tbl_permission_master',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
