# Generated by Django 5.2.11 on 2026-07-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospApp', '0077_add_permission_master'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PermissionMaster',
        ),
        migrations.AddField(
            model_name='tblroles',
            name='header_pages',
            field=models.ManyToManyField(blank=True, related_name='header_roles', to='hospApp.submenu'),
        ),
    ]
