# Generated by Django 5.2.11 on 2026-07-10 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospApp', '0078_delete_permissionmaster_tblroles_header_pages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newinvmaster',
            options={},
        ),
    ]
