# Generated by Django 5.2.11 on 2026-07-10 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospApp', '0079_alter_newinvmaster_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='newinvmaster',
            name='abnormal_values',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='newinvmaster',
            name='child_age_cutoff',
            field=models.FloatField(blank=True, default=12, null=True),
        ),
        migrations.AddField(
            model_name='newinvmaster',
            name='child_high',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newinvmaster',
            name='child_low',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newinvmaster',
            name='female_high',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newinvmaster',
            name='female_low',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newinvmaster',
            name='male_high',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newinvmaster',
            name='male_low',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newinvmaster',
            name='result_type',
            field=models.CharField(choices=[('numeric', 'Numeric'), ('text_choice', 'Text Choice'), ('free_text', 'Free Text')], default='numeric', max_length=20),
        ),
    ]
