# Generated by Django 5.2.11 on 2026-07-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospApp', '0080_newinvmaster_abnormal_values_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='recognized_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
