# Generated by Django 5.2.11 on 2026-07-24 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospApp', '0081_prescription_recognized_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='next_visit_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
