# Generated by Django 5.2.11 on 2026-07-24 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospApp', '0082_prescription_next_visit_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription3',
            name='next_visit_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
