# Generated by Django 5.2.11 on 2026-07-24 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospApp', '0083_prescription3_next_visit_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SittingsPage',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('uhid', models.CharField(max_length=50)),
                ('billno', models.CharField(max_length=50)),
                ('sitting', models.CharField(blank=True, max_length=100, null=True)),
                ('sdate', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
