# Generated by Django 5.2.11 on 2026-07-25 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospApp', '0084_sittingspage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sittingspage',
            name='next_sitting_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
