# Generated by Django 5.2.11 on 2026-08-10 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospApp', '0085_sittingspage_next_sitting_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbluserpermission',
            name='app_permission',
            field=models.BooleanField(default=False),
        ),
    ]
